# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - AcademicGBT

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://academicgbt.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5fa0a5136a66432995cc22e0fbb55fb9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2f76429f400240798b4a29db17228213 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: academicgbt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5fa0a5136a66432995cc22e0fbb55fb9 }}/AcademicGBT:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AcademicGBT'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_22f0069894bd47f892cb1430f58be06f }}
        images: 'academicgbt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5fa0a5136a66432995cc22e0fbb55fb9 }}/AcademicGBT:${{ github.sha }}'